### PR TITLE
New features

### PR DESCRIPTION
**Pull request by DRSchlaubi**
- [x] Auto convert to Kotlin DSL from pasted groovy snippets (plugins and dependencies)
- [x] Add quickfix for deprecated compile dependency config
- [x] Auto convert between ":" notation and
- [ ] Fix Settings UI
- [x] Acknowledge Global dependency format
- [x] Use selected dependency format for Groovy converter

# Preview Version
A preview version is available on the eap repo: https://plugins.jetbrains.com/plugins/eap/list

### CODE REVIEW

**Comment by DRSchlaubi** [comment]
News about the EAP release can be seen here: https://www.reddit.com/r/Kotlin/comments/mvs5eo/i_just_made_a_intellij_plugin_which_makes_the/

**Comment by DRSchlaubi** [comment]
# How to add the EAP?
In order to add the EAP you first have to add the EAP repo
1. Go to IntelliJ Settings (File -> Settings) -> Plugins
2. Hit the little gear symbol next to installed in the top right 
3. Click manage plugin repositories
4. Add https://plugins.jetbrains.com/plugins/eap/list

Then you should see the Version 2.0-RC1
If you don't download it manually from here: https://plugins.jetbrains.com/plugin/15341-gradleupdater/versions/eap/117802

**Comment by DRSchlaubi** [comment]
# How to add the EAP?
1. Go to File -> Settings -> Plugin
2. Hit the gear icon an the top right
3. Manage Plugin Repositories
4. Add https://plugins.jetbrains.com/plugins/eap/list
5. Add the Plugin
**Note** Please make sure that you have the latest version which is `2.0-RC1` at this time if it's not there download the latest version from here: https://plugins.jetbrains.com/plugin/15341-gradleupdater/versions/eap

**Comment by sanity** [comment]
Followed instructions for plugin, got this exception:

```
kotlin.UninitializedPropertyAccessException: lateinit property latestGradleVersion has not been initialized
	at me.schlaubi.intellij_gradle_version_checker.GradleVersionKt.getLatestGradleVersion(GradleVersion.kt:45)
	at me.schlaubi.intellij_gradle_version_checker.gradle_inspector.ProjectGradleVersionCheckingActivity.runActivity(ProjectGradleVersionCheckingActivity.kt:53)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$extensionAdded$0(StartupManagerImpl.java:278)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$extensionAdded$1(StartupManagerImpl.java:277)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by DRSchlaubi** [comment]
> Followed instructions for plugin, got this exception:
> 
> ```
> kotlin.UninitializedPropertyAccessException: lateinit property latestGradleVersion has not been initialized
> 	at me.schlaubi.intellij_gradle_version_checker.GradleVersionKt.getLatestGradleVersion(GradleVersion.kt:45)
> 	at me.schlaubi.intellij_gradle_version_checker.gradle_inspector.ProjectGradleVersionCheckingActivity.runActivity(ProjectGradleVersionCheckingActivity.kt:53)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$extensionAdded$0(StartupManagerImpl.java:278)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
> 	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$extensionAdded$1(StartupManagerImpl.java:277)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ```

That looks like the startup activity run could you grab the full IntelliJ log because the actual error happened before you got the exception

**Comment by DRSchlaubi** [comment]
Okay I figured out the bug happens if you install the plugin without restarting

**Comment by DRSchlaubi** [comment]
# 2.0-RC2
## Fixes
- the convert dialog now remembers you clicking the checkbox
- the exception when installing without restarting now has a workaround
## New Features
- Inspections on Kotlin dependencies


# Download

Currently awaiting approval.
Manual download: https://plugins.jetbrains.com/plugin/15341-gradleupdater/versions/eap/118139

**Pull request merged**
